# Home Manager configuration for mostafa user
# Manages user packages, dotfiles, and program configurations
{ config, lib, ... }:

{
  home.username = "mostafa";
  home.homeDirectory = "/home/mostafa";
  home.stateVersion = "25.11";

  # Disable nixpkgs version check (HM 26.05 with Nixpkgs 25.11)
  home.enableNixpkgsReleaseCheck = false;

  # === GIT ===
  programs.git = {
    enable = true;
    settings = {
      user = {
        name = "Mostafa";
        email = "Mostafa0Mohamed2002@gmail.com";
      };
      init.defaultBranch = "main";
      core.editor = "nvim";
    };
  };

  # === NEOVIM / VIM ===
  # Basic nvim setup - config is symlinked below
  programs.neovim = {
    enable = false;  # Disabled to avoid conflicts with manual config
  };

  # Symlink nvim config file for live editing (don't manage with neovim program)
  home.file.".config/nvim/init.lua" = {
    source = config.lib.file.mkOutOfStoreSymlink "/home/mostafa/nixos-config/dotfiles/nvim/init.lua";
  };

  # === GHOSTTY TERMINAL ===
  # Ghostty config will be symlinked from dotfiles/ghostty/config
  home.file.".config/ghostty/config" = {
    source = config.lib.file.mkOutOfStoreSymlink "/home/mostafa/nixos-config/dotfiles/ghostty/config";
  };

  # === MIME TYPES / DEFAULT APPLICATIONS ===
  xdg.mimeApps = {
    enable = true;
    defaultApplications = {
      "x-scheme-handler/http" = "firefox.desktop";
      "x-scheme-handler/https" = "firefox.desktop";
      "x-scheme-handler/chrome" = "firefox.desktop";
      "text/html" = "firefox.desktop";
      "application/x-extension-htm" = "firefox.desktop";
      "application/x-extension-html" = "firefox.desktop";
      "application/x-extension-shtml" = "firefox.desktop";
      "application/xhtml+xml" = "firefox.desktop";
      "application/x-extension-xhtml" = "firefox.desktop";
      "application/x-extension-xht" = "firefox.desktop";
    };
  };

  # Force Home Manager to take over existing mimeapps.list
  xdg.configFile."mimeapps.list".force = true;

  # === FIREFOX ===
  programs.firefox = {
    enable = true;
  };

  # === HTOP ===
  programs.htop = {
    enable = true;
  };

  # === BASH ===
  programs.bash = {
    enable = true;
    bashrcExtra = ''
      # Custom bash configuration
      export EDITOR=nvim
    '';
  };

  # === USER SHELL PACKAGES ===
  # User-specific packages (complementary to system packages)
  home.packages = [ ];

  # === SYSTEMD USER SERVICES ===
  # These are already managed by Home Manager internals
  # (ghostty service is handled by programs.ghostty if enabled)
  # User systemd services can be added here if needed

  # Don't manage these directories/files (GNOME manages them)
  xdg.configFile."dconf/user".enable = false;
  xdg.configFile."gtk-3.0".enable = false;
  xdg.configFile."gtk-4.0".enable = false;
  xdg.configFile."evolution".enable = false;
  xdg.configFile."Code".enable = false;
  xdg.configFile."VSCodium".enable = false;

  # Keep user-dirs.dirs as-is (auto-generated by system)
  xdg.configFile."user-dirs.dirs".enable = false;
}
